### PR TITLE
Add support for section index pages

### LINKED ISSUE #17: Add support for section index pages
Hey there!

Firstly, thank you so much for this amazing tool!

In our company, we use it in combo with [MkDocs Material](https://squidfunk.github.io/mkdocs-material/). Not sure about original MkDocs, but in this version, there is an option to set index pages for sections. To get a better understanding, please take a look at [feature description](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages).

It's very simple, and what it means, is that basically you may now have a nav entry in `mkdocs.yml` that looks like this:
```yaml
nav:
  - Home: index.md
  - Section:
    - section/index.md                             #   <--- this right here is new!
    - Page 1: section/page-1.md
    ...
    - Page n: section/page-n.md
```

Those kind of entries are currently not supported and result in "Error merging the "nav" entry in the site:   xxxx".

I've taken a quick look at the code - to me seems like a new elif in recursive function `update_navs` should be added where `nav` can be instance of `str`, or sth like that. 

I hope you'll have a bit of time to consider this.

Thanks!

### PR DESCRIPTION
**Pull request by Acerinth**
Closes #17

### CODE REVIEW

**Comment by ovasquez** [comment]
Hi @Acerinth, thanks for the interest in this tool and for adding support for this feature! 💯 
Do you know how this new item would look like in a test like the ones written in this file? https://github.com/ovasquez/mkdocs-merge/blob/main/mkdocsmerge/tests/merge_test.py
I ask because I want to make sure this feature doesn't break in the future, so ideally we would have a test to make sure it keeps working as expected in future releases.

**Comment by Acerinth** [comment]
Hey @ovasquez , thanks for such a quick response!

Yes, definitely. I've already thought about it, but I wanted to check with you before implementation. Should I just adjust the mocks in all three existing tests, or do you want me to create a completely new test? As this is not a new function, but just a change to the existing one, to me the first option makes more sense. What do you think?

**Comment by ovasquez** [comment]
@Acerinth I think a separate test would be better, because it can be focused on this feature, and in case it breaks, it would be easier to identify which feature broke. Does this make sense?

**Comment by Acerinth** [comment]
@ovasquez Sure, no problem. I've added a separate test now and double checked that it fails if my new 4 lines are not there ;) Is there anything else I should add/change?

**Comment by ovasquez** [comment]
Looks great to me. Thanks @Acerinth for adding the feature and the test!

**Pull request merged**
